# Site settings
title: My Blog
email: luzzardi@gmail.com
description: > # Test
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luzzardi.github.io" # the base hostname & protocol for your site
twitter_username: luzzardi
github_username:  luzzardi

# Build settings
markdown: kramdown
